version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "25043:25043"
    volumes:
      - ./backend:/app
    environment:
      - DEV_MODE=true

  frontend:
    build: ./frontend
    ports:
      - "25044:25044"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend 