version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "25043:25043"
    volumes:
      - ./backend:/app
    environment:
      - DEV_MODE=true
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:25043/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "25044:25044"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:25043
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.33.0/24 