version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    environment:
      - GIN_MODE=release
      - HOST=0.0.0.0
      - PORT=25044
      - GO111MODULE=on
      - GOFLAGS=-v
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  frontend:
    build:
      context: ./frontend
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://103.253.20.13:25044
      - PORT=25043
      - DEBUG=serve*
    volumes:
      - ./frontend:/app
      - /app/node_modules
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
